import { Company, Order, Product, Seller } from "./types";

const CATALOG =
  "https://haurszcvivpqdyenfwbb.supabase.co/storage/v1/object/public/product-images/catalog";

export const companies: Company[] = [
  {
    id: "c1",
    name: "Andijon Gaz Ta'minot",
    rating: 4.8,
    reviewCount: 214,
    address: "Andijon shahri, Bobur shoh ko'chasi 108",
    district: "Andijon shahri",
    phone: "+998 74 225 10 10",
    workingHours: "08:00 - 22:00",
    isAvailable: true,
    deliveryFee: 15000,
    tags: ["Sertifikatlangan", "Tez yetkazish"],
    joinedAt: "2024-02-11",
  },
  {
    id: "c2",
    name: "Asaka Energiya Servis",
    rating: 4.6,
    reviewCount: 158,
    address: "Asaka tumani, Mustaqillik ko'chasi 24",
    district: "Asaka",
    phone: "+998 74 225 20 20",
    workingHours: "09:00 - 21:00",
    isAvailable: true,
    deliveryFee: 20000,
    tags: ["Ommabop"],
    joinedAt: "2024-03-02",
  },
  {
    id: "c3",
    name: "Shahrixon Gaz Ta'minot",
    rating: 4.5,
    reviewCount: 97,
    address: "Shahrixon tumani, Navoiy ko'chasi 12",
    district: "Shahrixon",
    phone: "+998 74 225 30 30",
    workingHours: "24/7",
    isAvailable: true,
    deliveryFee: 22000,
    tags: ["24/7"],
    joinedAt: "2024-04-18",
  },
  {
    id: "c4",
    name: "Xo'jaobod Metan Servis",
    rating: 4.7,
    reviewCount: 132,
    address: "Xo'jaobod tumani, Istiqlol ko'chasi 45",
    district: "Xo'jaobod",
    phone: "+998 74 225 40 40",
    workingHours: "08:00 - 20:00",
    isAvailable: false,
    deliveryFee: 28000,
    tags: [],
    joinedAt: "2024-01-25",
  },
  {
    id: "c5",
    name: "Marhamat Sanoat Gaz",
    rating: 4.4,
    reviewCount: 76,
    address: "Marhamat tumani, Amir Temur ko'chasi 7",
    district: "Marhamat",
    phone: "+998 74 225 50 50",
    workingHours: "08:00 - 23:00",
    isAvailable: true,
    deliveryFee: 26000,
    tags: [],
    joinedAt: "2024-05-06",
  },
  {
    id: "c6",
    name: "Andijon GazPlus",
    rating: 4.9,
    reviewCount: 301,
    address: "Andijon shahri, Buyuk Ipak Yo'li 61",
    district: "Andijon shahri",
    phone: "+998 74 225 60 60",
    workingHours: "24/7",
    isAvailable: true,
    deliveryFee: 0,
    tags: ["Yetkazish bepul", "24/7"],
    joinedAt: "2023-11-30",
  },
  {
    id: "c7",
    name: "Baliqchi Gaz Ta'minot",
    rating: 0,
    reviewCount: 0,
    address: "Baliqchi tumani, Mustaqillik ko'chasi 3",
    district: "Baliqchi",
    phone: "+998 74 225 70 70",
    workingHours: "09:00 - 20:00",
    isAvailable: false,
    deliveryFee: 18000,
    tags: [],
    joinedAt: "2025-09-01",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Gaz ballon 50L",
    imageUrl: `${CATALOG}/gazBallon.jpg`,
    price: 120000,
    oldPrice: 135000,
    rating: 4.8,
    reviewCount: 214,
    isAvailable: true,
    isPopular: true,
    companyId: "c1",
    companyName: "Andijon Gaz Ta'minot",
    categoryId: "gazBallon",
    description: "50 litrlik po'lat gaz ballon — uy xo'jaligi va kichik tijorat uchun.",
    unit: "dona",
    moderationStatus: "approved",
    createdAt: "2024-02-12",
  },
  {
    id: "p2",
    name: "Gaz ballon 25L",
    imageUrl: `${CATALOG}/gazBallon.jpg`,
    price: 76000,
    rating: 4.6,
    reviewCount: 143,
    isAvailable: true,
    isPopular: true,
    companyId: "c2",
    companyName: "Asaka Energiya Servis",
    categoryId: "gazBallon",
    description: "Kichik uy xo'jaligi uchun qulay 25 litrlik ballon.",
    unit: "dona",
    moderationStatus: "approved",
    createdAt: "2024-03-04",
  },
  {
    id: "p3",
    name: "Propan ballon 27L",
    imageUrl: `${CATALOG}/propanGaz.jpg`,
    price: 62000,
    rating: 4.3,
    reviewCount: 58,
    isAvailable: true,
    isPopular: false,
    companyId: "c3",
    companyName: "Shahrixon Gaz Ta'minot",
    categoryId: "propanGaz",
    description: "Yuqori tozalikdagi suyultirilgan propan gazi.",
    unit: "dona",
    moderationStatus: "approved",
    createdAt: "2024-04-20",
  },
  {
    id: "p4",
    name: "Metan gaz (CNG)",
    imageUrl: `${CATALOG}/metanGaz.jpg`,
    price: 45000,
    rating: 4.5,
    reviewCount: 89,
    isAvailable: false,
    isPopular: false,
    companyId: "c5",
    companyName: "Marhamat Sanoat Gaz",
    categoryId: "metanGaz",
    description: "Avtomobillar uchun siqilgan tabiiy gaz.",
    unit: "m³",
    moderationStatus: "approved",
    createdAt: "2024-05-08",
  },
  {
    id: "p5",
    name: "Suyultirilgan gaz",
    imageUrl: `${CATALOG}/suyultirilganGaz.jpg`,
    price: 133000,
    oldPrice: 149000,
    rating: 4.9,
    reviewCount: 301,
    isAvailable: true,
    isPopular: true,
    companyId: "c6",
    companyName: "Andijon GazPlus",
    categoryId: "suyultirilganGaz",
    description: "Aholi uchun subsidiya narxidagi suyultirilgan gaz.",
    unit: "dona",
    moderationStatus: "approved",
    createdAt: "2023-12-02",
  },
  {
    id: "p6",
    name: "Elektr quvvatlash — 60 kVt",
    imageUrl: `${CATALOG}/elektrQuvvatlash.jpg`,
    price: 1200,
    rating: 4.7,
    reviewCount: 126,
    isAvailable: true,
    isPopular: false,
    companyId: "c6",
    companyName: "Andijon GazPlus Energy",
    categoryId: "elektrQuvvatlash",
    description: "Tezkor DC quvvatlash stansiyasi.",
    unit: "kVt·s",
    moderationStatus: "approved",
    createdAt: "2024-01-15",
  },
  {
    id: "p7",
    name: "Benzin AI-95",
    imageUrl: `${CATALOG}/benzin.jpg`,
    price: 12500,
    rating: 4.6,
    reviewCount: 412,
    isAvailable: true,
    isPopular: true,
    companyId: "c1",
    companyName: "Andijon Gaz Ta'minot",
    categoryId: "benzin",
    description: "Yevro-5 standartidagi AI-95 benzini.",
    unit: "litr",
    moderationStatus: "approved",
    createdAt: "2024-02-20",
  },
  {
    id: "p8",
    name: "Dizel Yevro-5",
    imageUrl: `${CATALOG}/dizel.jpg`,
    price: 13800,
    rating: 4.5,
    reviewCount: 174,
    isAvailable: true,
    isPopular: false,
    companyId: "c5",
    companyName: "Marhamat Sanoat Gaz",
    categoryId: "dizel",
    description: "Past oltingugurtli Yevro-5 dizel yoqilg'isi.",
    unit: "litr",
    moderationStatus: "approved",
    createdAt: "2024-05-11",
  },
  {
    id: "p9",
    name: "Gaz reduktori",
    imageUrl: `${CATALOG}/market.jpg`,
    price: 95000,
    rating: 4.2,
    reviewCount: 41,
    isAvailable: true,
    isPopular: false,
    companyId: "c3",
    companyName: "Shahrixon Gaz Ta'minot",
    categoryId: "market",
    description: "Ballon uchun bosim reduktori, manometr bilan.",
    unit: "dona",
    moderationStatus: "pending",
    createdAt: "2025-09-10",
  },
  {
    id: "p10",
    name: "Propan ballon 12L",
    imageUrl: `${CATALOG}/propanGaz.jpg`,
    price: 38000,
    rating: 4.1,
    reviewCount: 27,
    isAvailable: true,
    isPopular: false,
    companyId: "c2",
    companyName: "Asaka Energiya Servis",
    categoryId: "propanGaz",
    description: "Sayohat va dala sharoiti uchun ixcham propan ballon.",
    unit: "dona",
    moderationStatus: "pending",
    createdAt: "2025-09-11",
  },
  {
    id: "p11",
    name: "Metan konvertori",
    imageUrl: `${CATALOG}/metanGaz.jpg`,
    price: 3200000,
    rating: 0,
    reviewCount: 0,
    isAvailable: true,
    isPopular: false,
    companyId: "c1",
    companyName: "Andijon Gaz Ta'minot",
    categoryId: "metanGaz",
    description: "Avtomobilga o'rnatiladigan metan gaz konvertori to'plami.",
    unit: "dona",
    moderationStatus: "rejected",
    rejectionReason: "Mahsulot rasmiga texnik xavfsizlik sertifikati biriktirilmagan.",
    createdAt: "2025-09-08",
  },
  {
    id: "p12",
    name: "Motor moyi 4L",
    imageUrl: `${CATALOG}/market.jpg`,
    price: 285000,
    oldPrice: 320000,
    rating: 4.7,
    reviewCount: 63,
    isAvailable: true,
    isPopular: false,
    companyId: "c4",
    companyName: "Xo'jaobod Metan Servis",
    categoryId: "market",
    description: "Sintetik motor moyi 5W-40, 4 litrlik idishda.",
    unit: "dona",
    moderationStatus: "approved",
    createdAt: "2024-06-01",
  },
];

export const sellers: Seller[] = [
  {
    id: "c1",
    companyName: "Andijon Gaz Ta'minot",
    ownerName: "Sherzod Yo'ldoshev",
    category: "gazBallon",
    district: "Andijon shahri",
    address: "Bobur shoh ko'chasi 108",
    phone: "+998 74 225 10 10",
    status: "approved",
    createdAt: "2024-02-11",
    rating: 4.8,
    reviewCount: 214,
    productCount: 3,
  },
  {
    id: "c2",
    companyName: "Asaka Energiya Servis",
    ownerName: "Ilhomjon Qodirov",
    category: "gazBallon",
    district: "Asaka",
    address: "Mustaqillik ko'chasi 24",
    phone: "+998 74 225 20 20",
    status: "approved",
    createdAt: "2024-03-02",
    rating: 4.6,
    reviewCount: 158,
    productCount: 3,
  },
  {
    id: "c3",
    companyName: "Shahrixon Gaz Ta'minot",
    ownerName: "Otabek Mirzayev",
    category: "propanGaz",
    district: "Shahrixon",
    address: "Navoiy ko'chasi 12",
    phone: "+998 74 225 30 30",
    status: "approved",
    createdAt: "2024-04-18",
    rating: 4.5,
    reviewCount: 97,
    productCount: 2,
  },
  {
    id: "c4",
    companyName: "Xo'jaobod Metan Servis",
    ownerName: "Dilshod Ergashev",
    category: "metanGaz",
    district: "Xo'jaobod",
    address: "Istiqlol ko'chasi 45",
    phone: "+998 74 225 40 40",
    status: "suspended",
    createdAt: "2024-01-25",
    rating: 4.7,
    reviewCount: 132,
    productCount: 1,
  },
  {
    id: "c5",
    companyName: "Marhamat Sanoat Gaz",
    ownerName: "Bekzod Alimov",
    category: "dizel",
    district: "Marhamat",
    address: "Amir Temur ko'chasi 7",
    phone: "+998 74 225 50 50",
    status: "approved",
    createdAt: "2024-05-06",
    rating: 4.4,
    reviewCount: 76,
    productCount: 2,
  },
  {
    id: "c6",
    companyName: "Andijon GazPlus",
    ownerName: "Jahongir Tursunov",
    category: "suyultirilganGaz",
    district: "Andijon shahri",
    address: "Buyuk Ipak Yo'li 61",
    phone: "+998 74 225 60 60",
    status: "approved",
    createdAt: "2023-11-30",
    rating: 4.9,
    reviewCount: 301,
    productCount: 2,
  },
  {
    id: "c7",
    companyName: "Baliqchi Gaz Ta'minot",
    ownerName: "Aziz Nurmatov",
    category: "gazBallon",
    district: "Baliqchi",
    address: "Mustaqillik ko'chasi 3",
    phone: "+998 74 225 70 70",
    status: "pending",
    createdAt: "2025-09-01",
    rating: 0,
    reviewCount: 0,
    productCount: 0,
  },
  {
    id: "c8",
    companyName: "Buloqboshi Energiya",
    ownerName: "Sardor Yusupov",
    category: "elektrQuvvatlash",
    district: "Buloqboshi",
    address: "Mustaqillik ko'chasi 19",
    phone: "+998 74 225 80 80",
    status: "pending",
    createdAt: "2025-09-09",
    rating: 0,
    reviewCount: 0,
    productCount: 0,
  },
  {
    id: "c9",
    companyName: "Izboskan Gaz Ta'minot",
    ownerName: "Rustam Aliyev",
    category: "propanGaz",
    district: "Izboskan",
    address: "Yoshlik ko'chasi 5",
    phone: "+998 74 225 90 90",
    status: "rejected",
    createdAt: "2025-08-20",
    rating: 0,
    reviewCount: 0,
    productCount: 0,
  },
];

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "#GE234521",
    date: "2025-09-12T14:26:00",
    buyerName: "Nodira Yusupova",
    buyerPhone: "+998 90 111 22 33",
    companyId: "c1",
    companyName: "Andijon Gaz Ta'minot",
    items: [{ productName: "Gaz ballon 50L", quantity: 1, price: 120000 }],
    total: 135000,
    deliveryFee: 15000,
    status: "yolda",
    address: "Andijon shahri, Bog'ishamol ko'chasi 12",
  },
  {
    id: "o2",
    orderNumber: "#GE234498",
    date: "2025-09-10T09:14:00",
    buyerName: "Aziz Karimov",
    buyerPhone: "+998 93 333 44 55",
    companyId: "c6",
    companyName: "Andijon GazPlus",
    items: [{ productName: "Propan ballon 27L", quantity: 2, price: 62000 }],
    total: 134000,
    deliveryFee: 10000,
    status: "yetkazildi",
    address: "Asaka tumani, Mustaqillik ko'chasi 24",
  },
  {
    id: "o3",
    orderNumber: "#GE234410",
    date: "2025-09-06T18:02:00",
    buyerName: "Malika Tosheva",
    buyerPhone: "+998 97 123 45 67",
    companyId: "c2",
    companyName: "Asaka Energiya Servis",
    items: [{ productName: "Gaz ballon 25L", quantity: 1, price: 76000 }],
    total: 76000,
    deliveryFee: 0,
    status: "yetkazildi",
    address: "Andijon tumani, 12-mavze",
  },
  {
    id: "o4",
    orderNumber: "#GE234377",
    date: "2025-09-01T11:40:00",
    buyerName: "Bekzod Rashidov",
    buyerPhone: "+998 90 999 88 77",
    companyId: "c5",
    companyName: "Marhamat Sanoat Gaz",
    items: [{ productName: "Dizel Yevro-5", quantity: 40, price: 13800 }],
    total: 552000,
    deliveryFee: 0,
    status: "yetkazildi",
    address: "Shahrixon tumani, 19-kvartal",
  },
  {
    id: "o5",
    orderNumber: "#GE234610",
    date: "2025-09-12T08:05:00",
    buyerName: "Shahnoza Alieva",
    buyerPhone: "+998 95 555 66 77",
    companyId: "c1",
    companyName: "Andijon Gaz Ta'minot",
    items: [{ productName: "Benzin AI-95", quantity: 20, price: 12500 }],
    total: 250000,
    deliveryFee: 0,
    status: "tayyorlanmoqda",
    address: "Asaka tumani, 4-uy",
  },
  {
    id: "o6",
    orderNumber: "#GE234618",
    date: "2025-09-12T15:50:00",
    buyerName: "Farrux Egamberdiyev",
    buyerPhone: "+998 91 222 33 44",
    companyId: "c3",
    companyName: "Shahrixon Gaz Ta'minot",
    items: [{ productName: "Propan ballon 27L", quantity: 1, price: 62000 }],
    total: 84000,
    deliveryFee: 22000,
    status: "qabulQilindi",
    address: "Shahrixon tumani, Navoiy ko'chasi 30",
  },
  {
    id: "o7",
    orderNumber: "#GE234388",
    date: "2025-08-29T13:12:00",
    buyerName: "Umida Rahimova",
    buyerPhone: "+998 93 777 88 99",
    companyId: "c4",
    companyName: "Xo'jaobod Metan Servis",
    items: [{ productName: "Motor moyi 4L", quantity: 2, price: 285000 }],
    total: 570000,
    deliveryFee: 28000,
    status: "bekorQilindi",
    address: "Xo'jaobod tumani, Istiqlol ko'chasi 2",
  },
];

export function revenueByDay(days = 14) {
  const out: { date: string; revenue: number; orders: number }[] = [];
  const base = new Date("2025-09-12");
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(base);
    d.setDate(d.getDate() - i);
    const seed = d.getDate() + d.getMonth() * 3;
    const revenue = 1_800_000 + ((seed * 137) % 1_600_000);
    const ordersCount = 8 + ((seed * 7) % 20);
    const pad = (n: number) => (n < 10 ? `0${n}` : String(n));
    out.push({
      date: `${pad(d.getDate())}.${pad(d.getMonth() + 1)}`,
      revenue,
      orders: ordersCount,
    });
  }
  return out;
}
